on:
  push:
    branches:
      - main
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa 
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa 
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: connect, pull, build and remove old image
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && export JAVA_HOME=${{ secrets.JAVA_HOME }} && bash gradlew clean build && bash src/main/resources/scripts/cleanContainer.sh ${{ secrets.CONTAINER_NAME }}"

      - name: connect, deploy and cleanup
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && bash src/main/resources/scripts/createAndStart.sh ${{ secrets.APP_PORT }} ${{ secrets.CONTAINER_NAME }}"
      - name: cleanup
        run: rm -rf ~/.shh
